{"variants":[{"paths":["\/documentation\/answerbotsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/answerbotsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"metadata":{"title":"AnswerBotSDK","externalID":"AnswerBotSDK","role":"collection","symbolKind":"module","modules":[{"name":"AnswerBotSDK"}],"roleHeading":"Framework"},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"],"anchor":"Classes","title":"Classes"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/InteractionDataProtocol"],"anchor":"Protocols","title":"Protocols"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/InteractionData"],"anchor":"Structures","title":"Structures"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotSDKVersionString":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"AnswerBotSDKVersionString"}],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotSDKVersionString","kind":"symbol","title":"AnswerBotSDKVersionString","abstract":[{"text":"Project version string for AnswerBotSDK.","type":"text"}],"url":"\/documentation\/answerbotsdk\/answerbotsdkversionstring"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK":{"url":"\/documentation\/answerbotsdk","abstract":[],"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","title":"AnswerBotSDK"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/InteractionDataProtocol":{"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/InteractionDataProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InteractionDataProtocol"}],"url":"\/documentation\/answerbotsdk\/interactiondataprotocol","title":"InteractionDataProtocol","type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InteractionDataProtocol"}]},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/InteractionData":{"type":"topic","title":"InteractionData","navigatorTitle":[{"kind":"identifier","text":"InteractionData"}],"url":"\/documentation\/answerbotsdk\/interactiondata","role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/InteractionData","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InteractionData"}],"kind":"symbol"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine":{"type":"topic","title":"AnswerBotEngine","navigatorTitle":[{"kind":"identifier","text":"AnswerBotEngine"}],"url":"\/documentation\/answerbotsdk\/answerbotengine","role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotEngine"}],"kind":"symbol"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotSDKVersionNumber":{"fragments":[{"kind":"identifier","text":"AnswerBotSDKVersionNumber"}],"type":"topic","title":"AnswerBotSDKVersionNumber","kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotSDKVersionNumber","abstract":[{"text":"Project version number for AnswerBotSDK.","type":"text"}],"url":"\/documentation\/answerbotsdk\/answerbotsdkversionnumber","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"],"title":"Classes"},{"generated":true,"anchor":"Variables","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotSDKVersionNumber","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotSDKVersionString"],"title":"Variables"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"ZDKAnswerBotEngine","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKAnswerBotEngine"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKAnswerBotEngine"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/navigatorTitle","op":"replace"}]}]}