{"variants":[{"paths":["\/documentation\/answerbotsdk\/answerbotengine\/engine()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotsdk\/answerbotengine\/engine()"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engine","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","text":"AnswerBotEngine","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"engine","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine","text":"AnswerBotEngine","kind":"typeIdentifier"}],"modules":[{"name":"AnswerBotSDK"}],"title":"engine()","externalID":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine(cm)engineAndReturnError:","navigatorTitle":[{"text":"engineAndReturnError:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/engine()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","role":"collection","url":"\/documentation\/answerbotsdk","title":"AnswerBotSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine":{"url":"\/documentation\/answerbotsdk\/answerbotengine","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","type":"topic","abstract":[],"title":"AnswerBotEngine","navigatorTitle":[{"kind":"identifier","text":"AnswerBotEngine"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotEngine"}]},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/engine()":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/engine()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"engine"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"AnswerBotEngine","preciseIdentifier":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine"}],"url":"\/documentation\/answerbotsdk\/answerbotengine\/engine()","title":"engine()","abstract":[],"navigatorTitle":[{"text":"engineAndReturnError:","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"engineAndReturnError:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"engineAndReturnError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","text":"ZDKAnswerBotEngine","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"engineAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKAnswerBotEngine","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/title"},{"value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/fragments","op":"replace"},{"value":"engineAndReturnError:","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1engine()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1engine()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"engineAndReturnError:"}],"op":"replace"}]}]}