{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isConversationOngoing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Engine.isConversationOngoing(_:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotsdk\/answerbotengine\/isconversationongoing(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotsdk\/answerbotengine\/isconversationongoing(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"]]},"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/isConversationOngoing(_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isConversationOngoing"},{"kind":"text","text":"(("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"isConversationOngoing(_:)","modules":[{"name":"AnswerBotSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine(im)isConversationOngoing:","navigatorTitle":[{"kind":"identifier","text":"isConversationOngoing:"}]},"references":{"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/isConversationOngoing(_:)":{"type":"topic","role":"symbol","url":"\/documentation\/answerbotsdk\/answerbotengine\/isconversationongoing(_:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"isConversationOngoing:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isConversationOngoing"},{"kind":"text","text":"(("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/isConversationOngoing(_:)","title":"isConversationOngoing(_:)"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK":{"title":"AnswerBotSDK","url":"\/documentation\/answerbotsdk","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","role":"collection","kind":"symbol","type":"topic","abstract":[]},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine":{"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotEngine"}],"url":"\/documentation\/answerbotsdk\/answerbotengine","kind":"symbol","navigatorTitle":[{"text":"AnswerBotEngine","kind":"identifier"}],"title":"AnswerBotEngine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"isConversationOngoing:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isConversationOngoing:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isConversationOngoing:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#b)","kind":"typeIdentifier","text":"void (^)(_Bool)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isConversationOngoing:","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1isConversationOngoing(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1isConversationOngoing(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isConversationOngoing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/title","value":"ZDKAnswerBotEngine"},{"value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/fragments","op":"replace"}]}]}