{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKAnswerBotEngine) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotEngine"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/answerbotsdk\/answerbotengine"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/answerbotsdk\/answerbotengine"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/12MessagingAPI6EngineP","doc:\/\/com.zendesk.AnswerBotSDK\/12MessagingAPI10ObservableP","doc:\/\/com.zendesk.AnswerBotSDK\/@M@MessagingAPI@objc(pl)ZDKEngine","doc:\/\/com.zendesk.AnswerBotSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.AnswerBotSDK\/s7CVarArgP","doc:\/\/com.zendesk.AnswerBotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.AnswerBotSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.AnswerBotSDK\/SQ","doc:\/\/com.zendesk.AnswerBotSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/id","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onUpdate","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/transferOptionDescription"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/isConversationOngoing()","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/isConversationOngoing(_:)","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onEvent(_:)","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/start(messagingAPI:)","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/stop()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/engine()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/Engine-Implementations","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/Observable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotEngine"}],"title":"AnswerBotEngine","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine","modules":[{"name":"AnswerBotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBotEngine"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK"]]},"references":{"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/stop()":{"role":"symbol","title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/stop()","kind":"symbol","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/stop()"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK":{"role":"collection","title":"AnswerBotSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","kind":"symbol","type":"topic","url":"\/documentation\/answerbotsdk"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/isConversationOngoing(_:)":{"role":"symbol","title":"isConversationOngoing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConversationOngoing"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/isConversationOngoing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isConversationOngoing:"}],"url":"\/documentation\/answerbotsdk\/answerbotengine\/isconversationongoing(_:)"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine":{"role":"symbol","title":"AnswerBotEngine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotEngine"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnswerBotEngine"}],"url":"\/documentation\/answerbotsdk\/answerbotengine"},"doc://com.zendesk.AnswerBotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/s7CVarArgP"},"doc://com.zendesk.AnswerBotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/objc(cs)NSObject"},"doc://com.zendesk.AnswerBotSDK/@M@MessagingAPI@objc(pl)ZDKEngine":{"type":"unresolvable","title":"MessagingAPI.ZDKEngine","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/@M@MessagingAPI@objc(pl)ZDKEngine"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/start(messagingAPI:)":{"role":"symbol","title":"start(messagingAPI:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messagingAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingAPIProtocol","preciseIdentifier":"s:12MessagingAPI0A11APIProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/start(messagingAPI:)","kind":"symbol","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/start(messagingapi:)"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/Observable-Implementations":{"role":"collectionGroup","title":"Observable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/Observable-Implementations","kind":"article","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/observable-implementations"},"doc://com.zendesk.AnswerBotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/transferOptionDescription":{"role":"symbol","title":"transferOptionDescription","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transferOptionDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransferOptionDescription","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKTransferOptionDescription"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/transferOptionDescription","kind":"symbol","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/transferoptiondescription"},"doc://com.zendesk.AnswerBotSDK/12MessagingAPI10ObservableP":{"type":"unresolvable","title":"MessagingAPI.Observable","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/12MessagingAPI10ObservableP"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/Engine-Implementations":{"role":"collectionGroup","title":"Engine Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/Engine-Implementations","kind":"article","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/engine-implementations"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/engine()":{"role":"symbol","title":"engine()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"engine"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AnswerBotEngine","preciseIdentifier":"c:@M@AnswerBotSDK@objc(cs)ZDKAnswerBotEngine"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/engine()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"engineAndReturnError:"}],"url":"\/documentation\/answerbotsdk\/answerbotengine\/engine()"},"doc://com.zendesk.AnswerBotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/objc(pl)NSObject"},"doc://com.zendesk.AnswerBotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/SQ"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/id":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/id","kind":"symbol","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/id"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/onUpdate":{"role":"symbol","title":"onUpdate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUpdate"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"kind":"text","text":" : ("},{"kind":"typeIdentifier","text":"Update","preciseIdentifier":"s:12MessagingAPI6UpdateO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onUpdate","kind":"symbol","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/onupdate"},"doc://com.zendesk.AnswerBotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/SH"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/isConversationOngoing()":{"role":"symbol","title":"isConversationOngoing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConversationOngoing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/isConversationOngoing()","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/answerbotsdk\/answerbotengine\/isconversationongoing()"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/onEvent(_:)":{"role":"symbol","title":"onEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:12MessagingAPI5EventO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onEvent(_:)","kind":"symbol","type":"topic","url":"\/documentation\/answerbotsdk\/answerbotengine\/onevent(_:)"},"doc://com.zendesk.AnswerBotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.AnswerBotSDK/12MessagingAPI6EngineP":{"type":"unresolvable","title":"MessagingAPI.Engine","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/12MessagingAPI6EngineP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAnswerBotEngine"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBotEngine"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKAnswerBotEngine"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/isConversationOngoing(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/engine()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAnswerBotEngine"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1isConversationOngoing(_:)\/title","value":"isConversationOngoing:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1isConversationOngoing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isConversationOngoing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/title","value":"ZDKAnswerBotEngine"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBotEngine"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1engine()\/title","value":"engineAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine~1engine()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"engineAndReturnError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}