{"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotsdk\/answerbotengine\/id"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","externalID":"s:12AnswerBotSDK0aB6EngineC2idSSvp","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","modules":[{"name":"AnswerBotSDK"}],"title":"id"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Engine.id"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/id"},"references":{"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine":{"role":"symbol","url":"\/documentation\/answerbotsdk\/answerbotengine","title":"AnswerBotEngine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotEngine"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AnswerBotEngine"}],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/id":{"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/id","abstract":[],"url":"\/documentation\/answerbotsdk\/answerbotengine\/id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"id","kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK":{"abstract":[],"kind":"symbol","type":"topic","title":"AnswerBotSDK","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","role":"collection","url":"\/documentation\/answerbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/title","op":"replace","value":"ZDKAnswerBotEngine"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/fragments","op":"replace","value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/navigatorTitle","op":"replace","value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}