{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotsdk\/answerbotengine\/onevent(_:)"]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Event","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI5EventO"},{"text":")","kind":"text"}],"title":"onEvent(_:)","externalID":"s:12AnswerBotSDK0aB6EngineC7onEventyy12MessagingAPI0F0OF","modules":[{"name":"AnswerBotSDK"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onEvent(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Event","preciseIdentifier":"s:12MessagingAPI5EventO","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Engine.onEvent(_:)"},{"type":"text","text":"."}],"references":{"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK":{"abstract":[],"kind":"symbol","type":"topic","title":"AnswerBotSDK","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","role":"collection","url":"\/documentation\/answerbotsdk"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/onEvent(_:)":{"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onEvent(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Event","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI5EventO"},{"text":")","kind":"text"}],"type":"topic","title":"onEvent(_:)","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/answerbotsdk\/answerbotengine\/onevent(_:)"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine":{"role":"symbol","url":"\/documentation\/answerbotsdk\/answerbotengine","title":"AnswerBotEngine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotEngine"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AnswerBotEngine"}],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ZDKAnswerBotEngine","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/title"},{"op":"replace","value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/fragments"},{"op":"replace","value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/navigatorTitle"}]}]}