{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ObservableIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","kind":"typeIdentifier"},{"text":" : (","kind":"text"},{"text":"Update","preciseIdentifier":"s:12MessagingAPI6UpdateO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"text":" : (","kind":"text"},{"text":"Update","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6UpdateO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":"]","kind":"text"}],"modules":[{"name":"AnswerBotSDK"}],"title":"onUpdate","roleHeading":"Instance Property","externalID":"s:12AnswerBotSDK0aB6EngineC8onUpdateSDy12MessagingAPI20ObservableIdentifierOyAE0F0OcGvp","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onUpdate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotsdk\/answerbotengine\/onupdate"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Observable.onUpdate"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine"]]},"sections":[],"references":{"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK":{"url":"\/documentation\/answerbotsdk","abstract":[],"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK","title":"AnswerBotSDK"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine":{"type":"topic","title":"AnswerBotEngine","navigatorTitle":[{"kind":"identifier","text":"AnswerBotEngine"}],"url":"\/documentation\/answerbotsdk\/answerbotengine","role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotEngine"}],"kind":"symbol"},"doc://com.zendesk.AnswerBotSDK/documentation/AnswerBotSDK/AnswerBotEngine/onUpdate":{"title":"onUpdate","kind":"symbol","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/answerbotsdk\/answerbotengine\/onupdate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"text":" : (","kind":"text"},{"text":"Update","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6UpdateO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.zendesk.AnswerBotSDK\/documentation\/AnswerBotSDK\/AnswerBotEngine\/onUpdate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/title","value":"ZDKAnswerBotEngine"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/fragments","value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotSDK~1documentation~1AnswerBotSDK~1AnswerBotEngine\/navigatorTitle","value":[{"text":"ZDKAnswerBotEngine","kind":"identifier"}]}]}]}